# -*- coding: utf-8 -*-
"""simple-Regression.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eodKjEmmKqnQdkqrf35MyPlFy7Vz4Bfy
"""

x = [5, 3, -1, 2, 6]
y = [14, 6, -5.5, 3.5, 18]

X, Y, XiYi, Xi2 = 0, 0, 0, 0
n = len(x)
for i in range(n):
  X = X + x[i]
  Y = Y + y[i]
  XiYi = XiYi + x[i] * y[i]
  Xi2 = Xi2 + x[i] ** 2
print (n, X, Y, XiYi, Xi2)

w1 = (n * XiYi - X * Y)/(n * Xi2 - X ** 2)

w0 = (Y - w1 * X)/n